# Generated by Django 5.1.2 on 2024-10-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.SmallIntegerField(choices=[(1, 'Camisetas'), (2, 'Blusas'), (3, 'Camisas'), (4, 'Casacos'), (5, 'Jaquetas'), (6, 'Calças'), (7, 'Shorts'), (8, 'Saias'), (9, 'Vestidos'), (13, 'Calçados'), (14, 'Acessórios'), (15, 'Outros')])),
                ('tamanho', models.SmallIntegerField(choices=[(1, 'PP'), (2, 'P'), (3, 'M'), (4, 'G'), (5, 'GG'), (6, 'XG'), (7, 'XXG')])),
                ('cor', models.SmallIntegerField(choices=[(1, 'Preto'), (2, 'Branco'), (3, 'Cinza'), (4, 'Azul'), (5, 'Vermelho'), (6, 'Verde'), (7, 'Amarelo'), (8, 'Rosa'), (9, 'Roxo'), (10, 'Marrom'), (11, 'Bege'), (12, 'Laranja'), (13, 'Prata'), (14, 'Dourado'), (15, 'Estampado'), (16, 'Multicolorido')])),
                ('condicao', models.SmallIntegerField(choices=[(1, 'Novo com etiqueta'), (2, 'Novo sem etiqueta'), (3, 'Usado como novo'), (4, 'Usado em bom estado'), (5, 'Usado com sinais de desgaste')])),
                ('genero', models.SmallIntegerField(choices=[(1, 'Masculino'), (2, 'Feminino'), (3, 'Unissex')])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='roupas/foto')),
            ],
        ),
    ]
