# Generated by Django 5.1.2 on 2024-10-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roupa',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='roupa',
            name='preco',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
