# Generated by Django 5.1.2 on 2024-10-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0002_rename_nome_roupa_titulo_roupa_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
